### ISSUE TITLE
About evaluation on ReCTS dataset

### ISSUE THREAD

**Issue by zhangliang-04** [Yuliang-Liu/MultimodalOCR#16]
Dear authors,
Thank you for your open sourcing! I find there are evaluation results on **3000** images in **ReCTS** in the repo. However, this result is not present in the current Arxiv paper. What does this happen?
Also, the ReCTS dataset released in [google drive](https://drive.google.com/drive/folders/1plgZf4XIuiOGjx4b17E1rvTA2UKpZRe1) contains 102,895 **training** images, and there are 67,026 of them with gt annotation. Is the 3000 evaluation images the **subset** of the 67,026 training images?

**Comment by echo840** [comment]
Thank you for your attention. It has already updated in the newest Arxiv paper. And you can download the cropped images in the google cloud link TextRec.zip（Text Recognition） file. Due to the enormous time consumption of testing all of them, we use a subset of 3,000 images for testing.
