### ISSUE TITLE
About the ocr performance on CTW and IC15

### ISSUE THREAD

**Issue by Coobiw** [Yuliang-Liu/MultimodalOCR#18]
Hello! Thanks for your great work! I've run your code to evaluate the ocr ability of mini-gpt4(eva-g + vicuna-7b). In this setting, I get `0.504@IC15` and `0.498@CTW`, which is higher than the performance reported in Table.1 of your paper. I also check the setting of your paper, not finding the LLM used in mini-gpt4. Is it convenient to tell me about this? 

I also curious about the reason of the improvement, probably due to the random_seed? I can't really understand it. If possible, can you give me some advice? Sincerely thanks for your help and best wishes!

**Comment by echo840** [comment]
Thanks for your attention. One possible reason is that we did not fix the random seed during testing. The results of our inference are published in the "answer_save" directory. The llm model we used is vicuna13b.
