### ISSUE TITLE
Semantic - Non Semantic IIIT5K dataset

### ISSUE THREAD

**Issue by rohan598** [Yuliang-Liu/MultimodalOCR#19]
I am trying to reproduce the results of a few LMM on semantic and non-semantic split of IIIT5K. Can you please provide details of the 3000 images with words that have been selected for this process ?

Thank you!

@Yuliang-Liu @echo840

**Comment by echo840** [comment]
Of course, you can download the dataset generated by us through this link https://drive.google.com/file/d/1U45qCpi-HiFC6jq-eTfpZ1CGV_LTriAW/view?usp=drive_link.  Thanks.

**Comment by rohan598** [comment]
Thank you!
