### ISSUE TITLE
About evaluation code for vqa tasks including ChartQA and InfoVQA

### ISSUE THREAD

**Issue by situozhang** [Yuliang-Liu/MultimodalOCR#20]
@Yuliang-Liu @echo840 

Hello,

I've noticed that in the **latest version** of your [article](http://arxiv.org/abs/2305.07895), you've introduced some new VQA testing tasks to the benchmark, including infoVQA and ChartQA. However, I couldn't find the testing code for these tasks within this GitHub repository.

Could you please update the repository with the relevant testing code or provide guidance on how to test these new tasks?

Thank you for your attention to this matter.

Best regards.

**Comment by gordonhu608** [comment]
Same question. Releasing them would be really helpful.
