### ISSUE TITLE
ask for Blip-opt performance 

### ISSUE THREAD

**Issue by QuanWeiJie** [Yuliang-Liu/MultimodalOCR#21]
Hello! Thanks for your great work! I am confused why library reported two results about Blip-opt ,'opt' and 'opt_hugging'. why the performance of the latter is much higher than the former, and my test result is very low!!

**Comment by echo840** [comment]
When using the inference code on Hugging Face, the accuracy of text recognition is high, but the model outputs nothing for the VQA tasks. Conversely, when using the LAVIS library for inference, the accuracy of text recognition is low, while the VQA accuracy is normal. It is possible that there might be some issues with the model's interface process.

**Comment by QuanWeiJie** [comment]
Thanks for your reply
