### ISSUE TITLE
The leaderboard is inaccessible...

### ISSUE THREAD

**Issue by zhimin-z** [Yuliang-Liu/MultimodalOCR#23]
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/8592144/47a5f506-0a7a-4aef-a8ca-77dd0b688d11)
I am clicking on this link:
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/8592144/11ebe63e-f090-48d8-9374-0cfd859c1e27)

**Comment by echo840** [comment]
Hello, I forgot to change the IP address here, but now it's OK.

**Comment by zhimin-z** [comment]
> Hello, I forgot to change the IP address here, but now it's OK.

Great, it redirects correctly to https://huggingface.co/spaces/echo840/ocrbench-leaderboard now :)
