### ISSUE TITLE
关于OCRBench评估

### ISSUE THREAD

**Issue by geknow** [Yuliang-Liu/MultimodalOCR#24]
请教一下，有几个问题
1. OCRBench里面，是从各个dataset抽取一部分image出来做评测，数据量不足，会不会评估结果不可信？
2. 这些image的answer是自己人工填的吗？例如cute80在官方github repo上只有image而没有提供答案的。

**Comment by echo840** [comment]
您好，OCRBench里面确实是从各个dataset抽取一部分image出来做评测，其中所有问答对都经过人工校验，关于数据量，OCRBench只包含1000个问答对，方便大家快速而准确地评估多模态大模型的OCR能力，此外我们在论文中也提供了FullTest的结果。OCRBench的这些image的answer不是人工填的，只不过进行了人工校验（修改错误的答案，提供答案其他可能对的形式），CUTE80原本就有标注，然后KIE的数据集是转成qa的格式。

**Comment by geknow** [comment]
> 您好，OCRBench里面确实是从各个dataset抽取一部分image出来做评测，其中所有问答对都经过人工校验，关于数据量，OCRBench只包含1000个问答对，方便大家快速而准确地评估多模态大模型的OCR能力，此外我们在论文中也提供了FullTest的结果。OCRBench的这些image的answer不是人工填的，只不过进行了人工校验（修改错误的答案，提供答案其他可能对的形式），CUTE80原本就有标注，然后KIE的数据集是转成qa的格式。

CUTE80的官方标注我一直没找到，应该是一些其他人的手工标注。麻烦发一下链接，非常感谢🙏

**Comment by geknow** [comment]
> 您好，OCRBench里面确实是从各个dataset抽取一部分image出来做评测，其中所有问答对都经过人工校验，关于数据量，OCRBench只包含1000个问答对，方便大家快速而准确地评估多模态大模型的OCR能力，此外我们在论文中也提供了FullTest的结果。OCRBench的这些image的answer不是人工填的，只不过进行了人工校验（修改错误的答案，提供答案其他可能对的形式），CUTE80原本就有标注，然后KIE的数据集是转成qa的格式。

看了一下，FullTest对比OCRBench，好像就是dataset的数据更加多一点？FullTest是各个datasets都是完整的吗？

**Comment by geknow** [comment]
ct80官方的图片是
<img width="657" alt="image" src="https://github.com/Yuliang-Liu/MultimodalOCR/assets/17638142/52b522f1-a5ef-4af4-9dc0-cfa842dc019e">
而评测集里面的是
<img width="187" alt="image" src="https://github.com/Yuliang-Liu/MultimodalOCR/assets/17638142/e8ed219f-a498-4321-a428-4af4ac7cd9e7">

这种裁剪后的ocr识别，会不会降低了model的门槛？

**Comment by echo840** [comment]
> > 您好，OCRBench里面确实是从各个dataset抽取一部分image出来做评测，其中所有问答对都经过人工校验，关于数据量，OCRBench只包含1000个问答对，方便大家快速而准确地评估多模态大模型的OCR能力，此外我们在论文中也提供了FullTest的结果。OCRBench的这些image的answer不是人工填的，只不过进行了人工校验（修改错误的答案，提供答案其他可能对的形式），CUTE80原本就有标注，然后KIE的数据集是转成qa的格式。
> 
> CUTE80的官方标注我一直没找到，应该是一些其他人的手工标注。麻烦发一下链接，非常感谢🙏

您可以从这篇ECCV2022的论文中下载。https://github.com/baudm/parseq
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/87795401/ad923dae-404a-4541-90ac-a4fe8bcea634)

**Comment by echo840** [comment]
> ct80官方的图片是 <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/17638142/302530166-52b522f1-a5ef-4af4-9dc0-cfa842dc019e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzkxNzQsIm5iZiI6MTcwNzI3ODg3NCwicGF0aCI6Ii8xNzYzODE0Mi8zMDI1MzAxNjYtNTJiNTIyZjEtYTVlZi00YWY0LTlkYzAtY2ZhODQyZGMwMTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA0MDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOWRiYjJiMWQwODVhMmE3NzM2NDU0NGM5ODE5MWQzNzM0ZjliODIyOGU5Y2FmNTM0NWRiNjg3YmQ0YzY2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QlGfEVWfDgCLdzEp-AWmwEeitQVmdS8vj8y_4nMXZQ8"> 而评测集里面的是 <img alt="image" width="187" src="https://private-user-images.githubusercontent.com/17638142/302530241-e8ed219f-a498-4321-a428-4af4ac7cd9e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzkxNzQsIm5iZiI6MTcwNzI3ODg3NCwicGF0aCI6Ii8xNzYzODE0Mi8zMDI1MzAyNDEtZThlZDIxOWYtYTQ5OC00MzIxLWE0MjgtNGFmNGFjN2NkOWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA0MDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOWVkZTkxZTk2MWI3ZmI5YmYwMWEzNDVjNmY5NDJmNTUzZDUwNDQ0NTcwNWE1OTEzMjU0MWFmMDZkMmQxNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hiz2744obEdEj6T_LrsNeNg4g3sqX2KdImJDR2uRSlA">
> 
> 这种裁剪后的ocr识别，会不会降低了model的门槛？

这种整图在OCR领域一般是用来做文本检测和文本spotting的，而裁剪后的图像是用来做文本识别的。在论文中我们评测的是文本识别任务。文本识别任务大家都是用这种裁剪后的图片进行识别的，您可以参考这篇ECCV2022的论文https://github.com/baudm/parseq。
