### ISSUE TITLE
About ESTVQA

### ISSUE THREAD

**Issue by ZZZHANG-jx** [Yuliang-Liu/MultimodalOCR#27]
为什么ESTVQA用的是训练集进行测试，不是有带标注的4000+测试集吗

**Comment by echo840** [comment]
您好，他的测试集没有给GT标注，我们参考”Cross-Modal Attention Networks with Modality Disentanglement for Scene-Text VQA“这篇论文也自己划分了训练测试。而且我们评测的所有模型都没有在ESTVQA上面训练过。
