### ISSUE TITLE
Chinese OCRBench

### ISSUE THREAD

**Issue by SWHL** [Yuliang-Liu/MultimodalOCR#29]
感谢你们的工作，我将该工作中的中文OCR评测数据集做了整理，搞了一个[ChineseOCRBench](https://huggingface.co/datasets/SWHL/ChineseOCRBench)

有机会的话，可以多多交流学习。

**Comment by echo840** [comment]
非常感谢您的贡献！

**Comment by luyao-cv** [comment]
这个支持使用VLMEvalKit评测的吗？

**Comment by SWHL** [comment]
不支持哈，只是做了最简单的整理
