### ISSUE TITLE
What is the sampling or filtering stratege of Evaluation dataset？

### ISSUE THREAD

**Issue by ouyanglinke** [Yuliang-Liu/MultimodalOCR#3]
I notice that the num of samples shown in Table 1 is different from the actural num of samples in those datasets. For instance, in ICDAR2013, there are 1095 images in test folder, of which 1015 samples has valid text annotation (not empty or '###' or '#'). However, as it shows in Table 1 of the paper, 857 samples are used for eval.  Is there any filtering stratege applied? Thank you for your insight.

**Comment by echo840** [comment]
IC15 and IC13 have two versions each. You can refer to the paper https://arxiv.org/pdf/1904.01906.pdf.        “The 857-image set is a subset of the 1,015 set where words shorter than 3 characters are pruned.”
