### ISSUE TITLE
泄题风险

### ISSUE THREAD

**Issue by Joker316701882** [Yuliang-Liu/MultimodalOCR#30]
你好，论文中好像没有特别强调，从各个数据集中抽取OCRBench评测数据时，是否避开了各个子数据集的trainset，如果这些子数据集的训练数据被加入大模型训练过程中，OCRBench是否面临泄题风险？

**Comment by echo840** [comment]
您好，除了STVQA和ESTVQA，其他数据集都是从测试集或者验证集中抽取的。而STVQA和ESTVQA由于在写论文的时候，测试集并没有公布答案，我们会从中抽取一部分作为评测。根据我们的观察，目前的大模型几乎没有用STVQA和ESTVQA进行训练，大部分是zero-shot在这两个数据集上进行评测。因此泄题风险较小，感谢您的提醒，我们在V2会改进这一点。

**Comment by Joker316701882** [comment]
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/18679821/f9ac7b8f-db45-479b-8be5-eb0b931181bb)
用VQA训练的多模态模型，印象中挺多都用了ST-VQA...现在用能收集到的所有VQA数据训模型是常态，估计ESTVQA或多或少被cover了

**Comment by echo840** [comment]
我目前也只发现这一个。

**Comment by Joker316701882** [comment]
InternLM-XComposer2-4KHD
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/18679821/a1c9271e-d5f2-4ec0-9141-93eb9637f78d)

InternVL
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/18679821/018df8bb-cefd-49d9-8096-3322e9ca70f7)

M3IT
![image](https://github.com/Yuliang-Liu/MultimodalOCR/assets/18679821/3ae0f085-108b-460d-80ee-32576164ccf1)

还是挺多的

**Comment by echo840** [comment]
感谢提醒，V2我们会改正这一点。目前这两个数据集只占100张。
