### ISSUE TITLE
Could you please update InternVL2 series model to the OCRBench? 

### ISSUE THREAD

**Issue by cooleel** [Yuliang-Liu/MultimodalOCR#32]
They claimed super high on OCRBench in Opencompass
![Screenshot 2024-07-19 at 2 54 28 PM](https://github.com/user-attachments/assets/58cb6927-d30e-4615-94c6-555c63ea3c99)
Is it possible to update these to the OCRBench so we will know the detailed scores on different components? Thanks.

**Comment by echo840** [comment]
Thank you for your attention, I will update these results over the next few weeks. In addition, we are working on a more challenging OCRBenchV2, which may be released soon.

**Comment by echo840** [comment]
Hello, I have tested the results of internvl2 (1B-4B) and have updated them on the leaderboard. Additionally, you can download the model predictions from the following link: [link](https://drive.google.com/drive/folders/19JNF2OnLP2GDIW_7yae1Tsq88AOxX2HK).
