### ISSUE TITLE
ChineseOCRBench支持使用VLMEvalKit评测的吗？ 

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/MultimodalOCR#33]
[ChineseOCRBench](https://huggingface.co/datasets/SWHL/ChineseOCRBench)支持使用VLMEvalKit评测的吗？

**Comment by echo840** [comment]
您好，非常感谢您的关注，这个不支持VLMEvalKit评测，但是我们计划在OCRBenchV2中加入中文版本，到时候会支持VLMEvalKit评测的。
