### ISSUE TITLE
评估报错

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/MultimodalOCR#34]
python ./scripts/monkey.py --image_folder ./OCRBench_Images --OCRBench_file ./OCRBench/OCRBench.json --save_name Monkey_OCRBench --num_workers 1
Process 0 start.
python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "MultimodalOCR/./scripts/monkey.py", line 116, in <module>
    data.extend(results[i])
KeyError: 0

**Comment by echo840** [comment]
![image](https://github.com/user-attachments/assets/5142495e-dcdd-4306-b791-67f35b5ae577)

您好，由于是多进程进行评测，代码不会报具体的错误，您能把这里注释掉并且加上下面的一行，再运行看看报什么错吗？

**Comment by luyao-cv** [comment]
可以了，请问支持intervl2吗？我看有个internvl2_s的脚本，是否能评估internvl2-2B模型呢？

**Comment by echo840** [comment]
可以的，改模型路径就行了。

**Comment by luyao-cv** [comment]
谢谢，我试试哈
