### ISSUE TITLE
 ChineseOCRBench的能评估了吗？

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/MultimodalOCR#35]
您好，请问已经加入ChineseOCRBench的数据集进行评估了吗？

**Comment by echo840** [comment]
您好，非常感谢您的关注，这个不支持VLMEvalKit评测，但是我们计划在OCRBenchV2中加入中文版本，到时候会支持VLMEvalKit评测的。如果您要评估[link](https://huggingface.co/datasets/SWHL/ChineseOCRBench)，可以将这里的评测数据构建成[link](https://github.com/Yuliang-Liu/MultimodalOCR/blob/main/OCRBench/OCRBench.json)这种形式进行评估。

**Comment by nemonameless** [comment]
请问 OCRBenchV2 大概什么时候放出来呢？
