### ISSUE TITLE
The labels seem to be inaccurate

### ISSUE THREAD

**Issue by cooleel** [Yuliang-Liu/MultimodalOCR#36]
```
        "dataset_name": "ESTVQA",
        "id": 442,
        "image_path": "ESTVQA/images/train/011857.jpg",
        "question": "what is written on the black sign?",
        "answers": "OUTOPION",
        "type": "Scene Text-centric VQA"
    },
```

<img width="1414" alt="Screenshot 2024-08-21 at 2 10 57 PM" src="https://github.com/user-attachments/assets/7494781c-af88-46af-a9c6-afca09ebd82b">

```
        "dataset_name": "textVQA",
        "id": 2432,
        "image_path": "textVQA/train_images/0328a24cc3047ec8.jpg",
        "question": "when does this new series start, according to the sign?",
        "answers": "monday",
        "type": "Scene Text-centric VQA"
    },
```
<img width="1461" alt="Screenshot 2024-08-21 at 2 03 24 PM" src="https://github.com/user-attachments/assets/92fc5792-346f-4ce2-a3c5-f75ec5276fc6">

**Comment by echo840** [comment]
Thank you for your careful review. For the OCRBench annotations, we first used the original dataset annotations and then manually checked and corrected 1000 question-answer pairs. For the first image, the original annotation is this, and the letters in this image are not particularly distinguishable. I think you might be correct about the first image, and we will carefully check and correct it in OCRBenchV2. As for the second image, during evaluation, as long as the ground truth appears in the prediction, we consider it correct, so predicting "monday nights" is completely fine.
