### ISSUE TITLE
评估报错

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/MultimodalOCR#37]
评估完成的时候出现了data.extend(results[i]) KeyError: 1的报错，

当我注视掉代码，并且加入最后一行，设置--num_workers 1能跑通并且输出分数，这是为什么呢？

    # pool = Pool(processes=args.num_workers)
    # for i in range(len(data_list)):
    #     pool.apply_async(eval_worker, args=(args, data_list[i], i, output_queue))
    # pool.close()
    # pool.join()
    eval_worker(args, data_list[0], 0, output_queue)

**Comment by echo840** [comment]
您是在测试internvl2模型吗

**Comment by luyao-cv** [comment]
> 您是在测试internvl2模型吗
对的

**Comment by luyao-cv** [comment]
设置--num_workers 8，我debug看了下，我的数据被拆成8份，但是results的key只有0

**Comment by echo840** [comment]
有个小问题可能需要手动修改一下，您需要将https://huggingface.co/OpenGVLab/InternVL2-1B/blob/main/modeling_internvl_chat.py中的.cuda()手动修改为.to(self.device)，不然他会在多个进程中都指定为0卡。如果您是通过auto model下载的权重，这个文件应该在您目录下面的这个位置（{your dir path}/.cache/huggingface/modules/transformers_modules/OpenGVLab/InternVL2-1B/{id}/modeling_internvl_chat.py）。

![image](https://github.com/user-attachments/assets/806a177a-9091-419b-8a3f-f1ad017f8f92)

**Comment by luyao-cv** [comment]
非常感谢，已解决～
