### ISSUE TITLE
About the construction of "Non-Semantic Text Recognition" part

### ISSUE THREAD

**Issue by liziming5353** [Yuliang-Liu/MultimodalOCR#38]
Nice job! I am interested in the "Non-Semantic Text Recognition" part. It seems that the images are synthesized by a computer. Could you share the specific details of the synthesis? Or other methods?

**Comment by echo840** [comment]
Thank you for your interest in our work. We generate 'Non-Semantic Text Recognition' using [synthtiger](https://github.com/clovaai/synthtiger). The 'Non-Semantic Text' is generated based on the IIIT5k dictionary, but with the character order of the words shuffled.

**Comment by liziming5353** [comment]
So what template type did you use?

**Comment by echo840** [comment]
![image](https://github.com/user-attachments/assets/15a5184d-f22d-48ed-aad6-899a7807e5bc)

Hello, you can generate the text images using this code. I edited the YAML file based on 'examples/synthtiger/config_horizontal.yaml', only removing transformations like distortion, bending, and blurring. I couldn't find the code I used at the time, but I believe using the default configuration should also work fine. You can give it a try.

**Comment by liziming5353** [comment]
I'll try. Thank you so much!
