### ISSUE TITLE
Could you please update H2OVL-Mississippi series model to OCRBench? 

### ISSUE THREAD

**Issue by cooleel** [Yuliang-Liu/MultimodalOCR#39]
We would like to ask for the addition of our newly developed models to the OCRBench leaderboard. 
Our models are available at:
https://huggingface.co/h2oai/h2ovl-mississippi-800m
https://huggingface.co/h2oai/h2ovl-mississippi-2b

In our local tests using VLMEvalKit, the 800M model achieved the best text recognition score.
<img width="1120" alt="Screenshot 2024-10-31 at 10 01 18 AM" src="https://github.com/user-attachments/assets/c36925ee-6106-4851-a0e6-981e450f5280">

Those models are also updated in OpenCompass. as shown here: 
<img width="2261" alt="Screenshot 2024-10-31 at 11 52 41 AM" src="https://github.com/user-attachments/assets/0e548fbb-df19-4f39-9048-7b9b90910355">

If there’s any additional information or clarification needed to facilitate this, please feel free to reach out. We truly appreciate your consideration! 
Thank you very much.

**Comment by echo840** [comment]
Thank you for providing such great models. Their results have already been updated on the OCRBench leaderboard.

**Comment by cooleel** [comment]
Thank you very much for quickly updating the model results. 

The leaderboard is down at the moment. @echo840

**Comment by echo840** [comment]
Thank you for the reminder! I rebuilt the leaderboard, and now it's working fine.
![1730644890512](https://github.com/user-attachments/assets/0f2e97ab-2192-46a8-b1e4-a956721dc634)

**Comment by cooleel** [comment]
Perfect. Thank you! @echo840
