### ISSUE TITLE
How to select handwriting data from IAM dataset?

### ISSUE THREAD

**Issue by kydxh** [Yuliang-Liu/MultimodalOCR#40]
For handwriting data in OCRBench, how do you select data from IAM (https://fki.tic.heia-fr.ch/databases/download-the-iam-handwriting-database)? We have observed that the words contained in OCRBench appear relatively regular, so we would like to ask if there are any length or other sampling control strategies?
Thank you very much.

**Comment by echo840** [comment]
Hello, we filtered out answers with fewer than four letters from IAM and manually selected the remaining ones, excluding images that cannot be recognized by humans.
